### ISSUE TITLE
Problem downloading any type of music videos

### ISSUE THREAD

**Issue by Vorffeed** [stefanodvx/crunpyroll#30]
I can not download music videos every time I put the code of any video of this type I get an error of 403 content not available.

I ask from ignorance, this may be because the method used to call Music from crunpyrrol is obsolete, since on the web appears for this type of links as musicvideo?

I leave the error code:

`Traceback (most recent call last):
  File "C:\Users\Lina\Desktop\Crunpyrrol\Programas\crunpyroll_cr(1080p).py", line 131, in <module>
    asyncio.run(main())
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Lina\Desktop\Crunpyrrol\Programas\crunpyroll_cr(1080p).py", line 60, in main
    streams = await client.get_streams(episode_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\crunpyroll\methods\get_streams.py", line 28, in get_streams
    response = await self.api_request(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\crunpyroll\client.py", line 119, in api_request
    return Client.parse_response(response, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\crunpyroll\client.py", line 92, in parse_response
    raise CrunpyrollException(message)
crunpyroll.errors.CrunpyrollException: [403] {"error":"Content Not Available"}`

and the link to one of the videos that gives me the error:
`https://www.crunchyroll.com/es-es/watch/musicvideo/MV7DB0A85A/synthetic-sympathy`

**Comment by deathnoragami** [comment]
u fix this?
