### ISSUE TITLE
Error with crunpyroll authentication issues

### ISSUE THREAD

**Issue by Vorffeed** [stefanodvx/crunpyroll#31]
Apparently they have updated something in crunchy that can't be downloaded anymore, I get this error

```
Traceback (most recent call last):
  File "C:\Users\Lina\Desktop\Crunchyrill\Programas\crunpyroll_cr(720p).py", line 132, in <module>
    asyncio.run(main())
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Lina\Desktop\Crunchyrill\Programas\crunpyroll_cr(720p).py", line 53, in main
    await client.start()
  File "C:\Python311\Lib\site-packages\crunpyroll\client.py", line 73, in start
    return await self.session.authorize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\crunpyroll\session.py", line 41, in authorize
    response = await self._client.api_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\crunpyroll\client.py", line 119, in api_request
    return Client.parse_response(response, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\crunpyroll\client.py", line 92, in parse_response
    raise CrunpyrollException(message)
crunpyroll.errors.CrunpyrollException: [401] {"code":"auth.obtain_access_token.client_inactive","context":[],"error":"invalid_client"}
```

**Comment by Pixel-LH** [comment]
i have the same problem too

**Comment by Vorffeed** [comment]
One doubt that has nothing to do with this @Pixel-LH  have you been able to kill the chrunchyroll session after finishing each download, or do you have to go to the web and delete them manually?

**Comment by Davis092** [comment]
Does anyone know how to get the PUBLIC TOKEN form Crunchyroll?

**Comment by Pixel-LH** [comment]
> > > One doubt that has nothing to do with this @Pixel-LH have you been able to kill the chrunchyroll session after finishing each download, or do you have to go to the web and delete them manually?
> > 
> > 
> > I think it should be possible. I save the MPD locally during the session and close it after getting the KEY, and then call the downloader to download it.
> 
> I'm sorry, I don't know much about python programming and I only adapt small simple things that can help me ^^U if you know how to do it, could you pass me the code?

Actually I'd love to share it, but sorry I can't do it, since my download script is customized for my entire download system, it would take me a lot of time to separate it out, unfortunately I'm very busy with development recently Other things，sorry

**Comment by Pixel-LH** [comment]
![image](https://github.com/stefanodvx/crunpyroll/assets/63084641/5289d9bb-baf8-4486-aae6-9fa7e388e435)
![image](https://github.com/stefanodvx/crunpyroll/assets/63084641/9f9795ab-29f6-4c0c-9b1a-400666e01046)
I explored it myself and found that the parameters required for the direction token interface have been changed. After I modified the parameters according to the CR, it took effect and I can continue to work. I forgot to mention that the latest PUBLIC_TOKEN has been changed to " bm9haWhkZXZtXzZpeWcwYThsMHE6", as for this cookie, I am currently thinking about the process of this change.

**Comment by inks007** [comment]
See #32
