### ISSUE TITLE
ModuleFoundError : crunpyroll.methods.get_old_streams

### ISSUE THREAD

**Issue by R4H4T069** [stefanodvx/crunpyroll#35]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 1, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/crunpyroll/__init__.py", line 1, in <module>
    from .client import Client
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/crunpyroll/client.py", line 1, in <module>
    from .methods import Methods
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/crunpyroll/methods/__init__.py", line 11, in <module>
    from .get_old_streams import GetOldStreams
ModuleNotFoundError: No module named 'crunpyroll.methods.get_old_streams'

**Comment by Hartie95** [comment]
This should fix it, just need to get merged: #34

**Comment by Hartie95** [comment]
@stefanodvx The references only got removed partially, there is still the import, check my pull request for details.
